### ISSUE TITLE
Projection transformation or option

### ISSUE THREAD

**Issue by besquared** [vega/vega-transforms#1]
This is a bit less important for the vega renderer but can be useful if you're using dataflow as a standalone data processing engine.

If this was added it would probably be best as a param on collect similar to the sort param. Only caveat here is you probably want to be able to project aliases as well so the straight up array of strings param wouldn't quite cut it.

**Comment by jheer** [comment]
Thanks for the request! @leibatt had a request for this as well. I think a new operator will likely be needed for this, particularly if aliasing support is included. I'll look into this.

**Comment by jheer** [comment]
Added in 954e136ebb92bcd3673f12733e7e52b3e0a40c7d and released with vega-transforms v1.1.0. The Project transform will also be included in the next Vega release.

**Comment by besquared** [comment]
LOVE IT
