### ISSUE TITLE
Union transform

### ISSUE THREAD

**Issue by evanliomain** [vega/vega-transforms#10]
It would be useful to have a **concat** transform to concat two sources
e.g. 
```json
[{
  "name": "DataA",
  "values":[{ "foo": "A", "bar": 1}]
},
{
  "name": "DataB",
  "values":[{ "foo": "B", "bar": 2}],
  "transform": [
    {
      "type": "concat",
      "from": "DataA"
    }
  ]
}]
```

It results DataB to equals
```json
[{ "foo": "B", "bar": 2}, { "foo": "A", "bar": 1}]
```

**Comment by domoritz** [comment]
This is called union in database terms. 

You can actually do that already with a bit of a hack. Just provide an array of sources in a Vega data source. See https://vega.github.io/vega/docs/data/

Having said that, I requested a union transform before (have to find the issue).

**Comment by evanliomain** [comment]
Thanks @domoritz, I totally miss this nicety in vega docs.

Moreover, if it's a duplicate issue, it can be closed.

**Comment by domoritz** [comment]
I closed https://github.com/vega/vega-transforms/issues/10 in favor of this issue and changed the title.

**Comment by jheer** [comment]
Can you help me gain more insight into why an explicit transform is needed here? The existing union functionality does require defining a new (combined) data source, but is more balanced -- it doesn't have a notion of primary versus secondary data sources. Are there examples where this doesn't work well?

(For the record, I don't think of the current design as "a bit of a hack". I would agree that it is currently less discoverable, but that might be mitigated with updates to the documentation.)

**Comment by domoritz** [comment]
Yes, After thinking through it, I agree.
