### ISSUE TITLE
ci0 and ci1 aggregate operators produce inconsistent output

### ISSUE THREAD

**Issue by kanitw** [vega/vega-transforms#2]
Running it multiple times can produce different output values.
This may be due to the fact that it is from a bootstrap method. 
But we might be able to fix the random generator's seed to make the output consistent.  

Minimal VL spec to reproduce the problem

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {"url": "data/barley.json"},
  "mark": "text",
  "encoding": {
    "text": {
      "aggregate": "ci0", "field": "yield", "type": "quantitative"
    }
  }
}
```

cc: @arvind @domoritz -- This causes VL's `build:examples` script to change SVGs for specs that uses ci0, ci1 (`layer_area_ci` and `layer_error_bars`) every time we run it.   Please ignore those changes.

**Comment by jheer** [comment]
This is the intended behavior. We use the built-in JS `Math.random` which does not provide control over a random seed. We would need to introduce a new library to provide this functionality.

At this point I do not intend to change this behavior, and so you may need to drop these aggregates from your test suite. Vega already takes a similar approach with the wordcloud layout, which also depends on random numbers.

**Comment by jheer** [comment]
Note, in the future we might want to encapsulate our source of randomness to allow extension / replacement by third parties (including for testing purposes). For example, perhaps vega-util could have a random method that defaults to `Math.random` but can be swapped out for another implementation. We could then update all `Math.random` calls in the Vega code base to use the new utility instead. Such a scheme would not enable unique seeds for different operators, but would at least enable deterministic testing runs.

**Comment by jheer** [comment]
Also, FWIW the places that call `Math.random` are in the vega-wordcloud and vega-statistics repos. I believe that should be it, though it would be worth double-checking.

**Comment by jheer** [comment]
Note: Vega 3.0.3 now includes a new modular random number generator (defaults to `Math.random`), and all internal calls to random are routed to this. The only exceptions are a few calls to `Math.random` inside D3 for pack hierarchy layout and quad-tree construction.

To get deterministic results for testing, you can register your own seeded RNG using the `vega.setRandom` function. For an example using a basic linear congruential generator, see [Vega's scene-test](https://github.com/vega/vega/blob/master/test/scene-test.js#L15).
