### ISSUE TITLE
Pivot transform (feature request)

### ISSUE THREAD

**Issue by ericsoco** [vega/vega-transforms#5]
Per our discussion [here](https://groups.google.com/forum/#!topic/vega-js/6bF9ZC4H-vU), it would be useful to have a pivot transform to turn e.g. `{city: 'SF', val: 10}` into `{SF: 10}`.

**Comment by jheer** [comment]
Added in vega-transforms@1.3.0. Will include in next Vega release!

**Comment by ericsoco** [comment]
So fast! Thanks Jeff!
