### ISSUE TITLE
Median of string array

### ISSUE THREAD

**Issue by domoritz** [vega/vega-transforms#8]
Currently does not work in impute because of https://github.com/d3/d3-array/issues/70 (https://github.com/vega/vega-transforms/blob/28743f46ffce75690ccd3a835814c914159d7d3a/src/Impute.js#L3) and not in aggregate because of https://github.com/vega/vega-transforms/blob/e9af8c0fb2cd6228432a433181655c78c98bde92/src/util/AggregateOps.js#L93.  

```json
{
  "$schema": "https://vega.github.io/schema/vega/v3.json",
  "data": [
    {
      "name": "source",
      "values": [
        {"x": 0, "id": "A", "name": "The A One"},
        {"x": 1, "id": "A", "name": "The A One"},
        {"x": 2, "id": "B", "name": "The B One"},
        {"x": 3, "id": "B", "name": "The B One"},
        {"x": 4, "id": "B", "name": "The B One"}
      ], 
      "transform": [
        {
          "type": "aggregate",
          "groupby": ["id"],
          "ops": ["mean", "median"],
          "fields": ["x", "name"],
          "as": ["mean_x", "tooltip"]
        }
      ]
    }
  ]
}
```

cc @jakevdp

**Comment by jheer** [comment]
The median of an arbitrary string array is not a well-defined operation. For example, when there are an even number of strings, one can not compute an intermediate value.

Unless perhaps you are requesting support for numerical strings that could/should be coerced to numbers? (If not, please close out the issue.)

**Comment by domoritz** [comment]
This is not a high priority feature but I actually mean median of string arrays. For even numbers, we could pick the n/2th item. Anyway, I don't have euse case other than it being nice to support median for all array types.

**Comment by jheer** [comment]
I tested this in R for a comparison: funny enough, it works for odd-length string vectors and then crashes on even-length vectors. So at least we are consistent.

**Comment by domoritz** [comment]
Numpy always complains.
